spring:
  datasource:
    url: jdbc:mysql://prosync1.cdy4gimmf78l.ap-northeast-2.rds.amazonaws.com:3306/PCLH
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: PCLH03101103
    schema:
      classpath: schema.sql
    hikari:
      maximum-pool-size: 130
      connection-timeout: 20000
      minimum-idle: 5
    sql:
      init:
        mode: always

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.study.mull

  jpa:
